version : "3"
services:
  db:
    container_name: db
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=stack_cms
      - MYSQL_USER=stack_cms
      - MYSQL_PASSWORD=password
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
      - ./mongodb:/data/configdb